[package]
name = "martythemaan/deadland"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ProfileStore = "acceierate2/profile-store@1.1.0"
ReplicaService = "madstudioroblox/replica-service@^0.2.0"
Cmdr = "evaera/cmdr@^1.8.0"
Promise = "evaera/promise@^4.0.0"